import type { Order } from "../types/thermoslip";

export const DEMO_ORDERS: Order[] = [
  {
    id: "gid://shopify/Order/demo-1001",
    name: "#1001",
    createdAt: new Date().toISOString(),
    customerName: "Alice Dupont",
    note: null,
    shippingMethod: "Colissimo Standard",
    shippingAddress: {
      name: "Alice Dupont",
      formatted: ["12 Rue de Rivoli"],
      city: "Paris",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-1",
        title: "Pack T-Shirts Coton Bio",
        variantTitle: "Noir / M",
        quantity: 3,
        unfulfilledQuantity: 3,
        requiresShipping: true,
        sku: "TSH-BLK-M",
        quantityToPack: 3,
      },
    ],
    printStatus: null,
    warnings: [{ code: "MULTI_QTY" }],
  },
  {
    id: "gid://shopify/Order/demo-1002",
    name: "#1002",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    customerName: "Bernard Lefebvre",
    note: "Sonner à l'interphone Bâtiment B svp",
    shippingMethod: "Mondial Relay",
    shippingAddress: {
      name: "Bernard Lefebvre",
      formatted: ["45 Av. Jean Jaurès"],
      city: "Lyon",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-2",
        title: "Tasse Céramique",
        variantTitle: "Blanc",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "MUG-WHT",
        quantityToPack: 1,
      },
    ],
    printStatus: null,
    warnings: [{ code: "CUSTOMER_NOTE" }],
  },
  {
    id: "gid://shopify/Order/demo-1003",
    name: "#1003",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    customerName: "Claire Martin",
    note: null,
    shippingMethod: "Chronopost Express 24h",
    shippingAddress: {
      name: "Claire Martin",
      formatted: ["8 Bd Haussmann"],
      city: "Paris",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-3",
        title: "Gourde Isotherme Inox",
        variantTitle: "Argent",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "BOT-SLV",
        quantityToPack: 1,
      },
    ],
    printStatus: null,
    warnings: [{ code: "EXPRESS" }],
  },
  {
    id: "gid://shopify/Order/demo-1004",
    name: "#1004",
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    customerName: "David Moreau",
    note: "Commande urgente pour anniversaire demain !",
    shippingMethod: "DHL Express Priority Delivery",
    shippingAddress: {
      name: "David Moreau",
      formatted: ["15 Rue de la Paix"],
      city: "Marseille",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-4a",
        title: "Sweat à Capuche",
        variantTitle: "Gris / L",
        quantity: 2,
        unfulfilledQuantity: 2,
        requiresShipping: true,
        sku: "HD-GRY-L",
        quantityToPack: 2,
      },
      {
        id: "gid://shopify/LineItem/demo-4b",
        title: "Casquette Vintage",
        variantTitle: "Bleu Marine",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "CAP-NVY",
        quantityToPack: 1,
      },
    ],
    printStatus: null,
    warnings: [
      { code: "MULTI_QTY" },
      { code: "CUSTOMER_NOTE" },
      { code: "EXPRESS" },
    ],
  },
  {
    id: "gid://shopify/Order/demo-1005",
    name: "#1005",
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    customerName: "Emma Petit",
    note: null,
    shippingMethod: "Standard Shipping",
    shippingAddress: {
      name: "Emma Petit",
      formatted: ["3 Rue Victor Hugo"],
      city: "Bordeaux",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-5",
        title: "Stylo Métal Gravé",
        variantTitle: null,
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "PEN-MET",
        quantityToPack: 1,
      },
    ],
    printStatus: "printed",
    warnings: [],
  },
  {
    id: "gid://shopify/Order/demo-1006",
    name: "#1006",
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    customerName: "François Dubois",
    note: "Grand colis d'équipement - livraison quai de déchargement",
    shippingMethod: "Colissimo Recommandé",
    shippingAddress: {
      name: "François Dubois",
      formatted: ["18 Rue de l'Industrie", "Bâtiment Logistique 4"],
      city: "Strasbourg",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-6-1",
        title: "T-Shirt Premium Coton Peigné Bio",
        variantTitle: "Noir / L",
        quantity: 2,
        unfulfilledQuantity: 2,
        requiresShipping: true,
        sku: "TSH-PREM-BLK-L",
        quantityToPack: 2,
      },
      {
        id: "gid://shopify/LineItem/demo-6-2",
        title: "T-Shirt Premium Coton Peigné Bio",
        variantTitle: "Blanc / M",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "TSH-PREM-WHT-M",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-3",
        title: "Sweat Zippé Capuche Molleton Épais",
        variantTitle: "Gris Anthracite / XL",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "HD-ZIP-ANTH-XL",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-4",
        title: "Pantalon Cargo Ripstop Renforcé",
        variantTitle: "Kaki / 34",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "PNT-CRG-KHK-34",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-5",
        title: "Casquette 5 Panels Coton Épais",
        variantTitle: "Vert Forêt",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "CAP-5P-GRN",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-6",
        title: "Chaussettes de Sport Respirantes Pack x3",
        variantTitle: "Noir / 42-45",
        quantity: 3,
        unfulfilledQuantity: 3,
        requiresShipping: true,
        sku: "SOX-SPO-BLK-42",
        quantityToPack: 3,
      },
      {
        id: "gid://shopify/LineItem/demo-6-7",
        title: "Sac à Dos Roll-Top Imperméable 25L",
        variantTitle: "Noir Mat",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "BAG-RLTP-25L",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-8",
        title: "Gourde Isotherme Double Paroi 750ml",
        variantTitle: "Acier Brossé",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "BOT-ISO-750",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-9",
        title: "Porte-Clés Mousqueton Aluminium Anodisé",
        variantTitle: "Orange Fluo",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "KEY-MSQ-ORN",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-10",
        title: "Bandana Multifonction Microfibre Sans Couture",
        variantTitle: "Camouflage Gris",
        quantity: 2,
        unfulfilledQuantity: 2,
        requiresShipping: true,
        sku: "BDN-MCF-CAM",
        quantityToPack: 2,
      },
      {
        id: "gid://shopify/LineItem/demo-6-11",
        title: "Gants Tactiles Mi-Saison Respirants",
        variantTitle: "Noir / Taille 9",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "GLV-TAC-BLK-9",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-12",
        title: "Trousse de Toilette Compacte Déperlante",
        variantTitle: "Gris Chiné",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "KIT-TOI-GRY",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-13",
        title: "Ceinture Tactique Boucle Métal Quick-Release",
        variantTitle: "Noir / 125cm",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "BLT-TAC-BLK-125",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-14",
        title: "Pack Stickers Vinyle Résistants aux Intempéries",
        variantTitle: "Assortiment Pack de 10",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "STK-VIN-10P",
        quantityToPack: 1,
      },
      {
        id: "gid://shopify/LineItem/demo-6-15",
        title: "Carnet de Notes Étanche Tout-Terrain A6",
        variantTitle: "Couverture Rigide Orange",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "NOT-WR-A6",
        quantityToPack: 1,
      },
    ],
    printStatus: null,
    warnings: [
      { code: "MULTI_QTY" },
      { code: "CUSTOMER_NOTE" },
    ],
  },
];
