import type { Order } from "../types/thermoslip";

export const DEMO_ORDERS: Order[] = [
  {
    id: "gid://shopify/Order/demo-1001",
    name: "#1001",
    createdAt: new Date().toISOString(),
    customerName: "Alice Dupont",
    note: null,
    shippingMethod: "Colissimo Standard",
    shippingAddress: {
      name: "Alice Dupont",
      formatted: ["12 Rue de Rivoli"],
      city: "Paris",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-1",
        title: "Pack T-Shirts Coton Bio",
        variantTitle: "Noir / M",
        quantity: 3,
        unfulfilledQuantity: 3,
        requiresShipping: true,
        sku: "TSH-BLK-M",
        quantityToPack: 3,
      },
    ],
    printStatus: null,
    warnings: [{ code: "MULTI_QTY" }],
  },
  {
    id: "gid://shopify/Order/demo-1002",
    name: "#1002",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    customerName: "Bernard Lefebvre",
    note: "Sonner à l'interphone Bâtiment B svp",
    shippingMethod: "Mondial Relay",
    shippingAddress: {
      name: "Bernard Lefebvre",
      formatted: ["45 Av. Jean Jaurès"],
      city: "Lyon",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-2",
        title: "Tasse Céramique",
        variantTitle: "Blanc",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "MUG-WHT",
        quantityToPack: 1,
      },
    ],
    printStatus: null,
    warnings: [{ code: "CUSTOMER_NOTE" }],
  },
  {
    id: "gid://shopify/Order/demo-1003",
    name: "#1003",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    customerName: "Claire Martin",
    note: null,
    shippingMethod: "Chronopost Express 24h",
    shippingAddress: {
      name: "Claire Martin",
      formatted: ["8 Bd Haussmann"],
      city: "Paris",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-3",
        title: "Gourde Isotherme Inox",
        variantTitle: "Argent",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "BOT-SLV",
        quantityToPack: 1,
      },
    ],
    printStatus: null,
    warnings: [{ code: "EXPRESS" }],
  },
  {
    id: "gid://shopify/Order/demo-1004",
    name: "#1004",
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    customerName: "David Moreau",
    note: "Commande urgente pour anniversaire demain !",
    shippingMethod: "DHL Express Priority Delivery",
    shippingAddress: {
      name: "David Moreau",
      formatted: ["15 Rue de la Paix"],
      city: "Marseille",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-4a",
        title: "Sweat à Capuche",
        variantTitle: "Gris / L",
        quantity: 2,
        unfulfilledQuantity: 2,
        requiresShipping: true,
        sku: "HD-GRY-L",
        quantityToPack: 2,
      },
      {
        id: "gid://shopify/LineItem/demo-4b",
        title: "Casquette Vintage",
        variantTitle: "Bleu Marine",
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "CAP-NVY",
        quantityToPack: 1,
      },
    ],
    printStatus: null,
    warnings: [
      { code: "MULTI_QTY" },
      { code: "CUSTOMER_NOTE" },
      { code: "EXPRESS" },
    ],
  },
  {
    id: "gid://shopify/Order/demo-1005",
    name: "#1005",
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    customerName: "Emma Petit",
    note: null,
    shippingMethod: "Standard Shipping",
    shippingAddress: {
      name: "Emma Petit",
      formatted: ["3 Rue Victor Hugo"],
      city: "Bordeaux",
      country: "France",
    },
    lineItems: [
      {
        id: "gid://shopify/LineItem/demo-5",
        title: "Stylo Métal Gravé",
        variantTitle: null,
        quantity: 1,
        unfulfilledQuantity: 1,
        requiresShipping: true,
        sku: "PEN-MET",
        quantityToPack: 1,
      },
    ],
    printStatus: "printed",
    warnings: [],
  },
];
