# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d6f5f485f916ddef3fb6a57db87a3a7"
name = "ThermoSlip Order Printer"
application_url = "https://thermoslip-order-printer.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app/scopes_update", "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders"

[auth]
redirect_urls = [
  "https://thermoslip-order-printer.fly.dev/auth/callback",
  "https://thermoslip-order-printer.fly.dev/auth/shopify/callback",
  "https://thermoslip-order-printer.fly.dev/api/auth"
]

[order.metafields.app.print_status]
name = "ThermoSlip print status"
type = "single_line_text_field"
